AlexKolpa/twodee-discord

.eslintrc.js, config/default.json5, package.json, src/index.js, src/plugins/news.js, src/plugins/reddit.js, yarn.lock
=> Set up news plugin

config/default.json5, src/index.js, src/plugins/emotes/db.js, src/plugins/emotes/index.js
Simple custom emotes, which allows for mods to add and remove emotes
=> Set up custom emotes

src/index.js, src/plugins/eightball.js, src/plugins/emotes/index.js
=> Add !8ball command

src/plugins/reddit.js
This ensures we have an image to show if we set the link
=> Check if submission url is image link

src/plugins/reddit.js
Before posting, check whether the submission hasn't been removed in the mean time.
=> Handle remove submissions

src/plugins/reddit.js
Adds filtering for recently posted Reddit urls to reduce spam.
=> Filter out recently posted urls

src/plugins/reddit.js
Post time comparison now correctly uses timestamps instead of dates.
=> Fix post age comparison in Reddit post filter

package.json, src/index.js, src/plugins/kyuu.js
Adds !kyuu command which retrieves a random page of Wonder Cat Kyuu-chan and posts it to the channel.
=> Add !kyuu to post a random Kyuu page

src/plugins/emotes/index.js
Fixes getting a reaction by id.
=> Fix getting a reaction by id.

src/index.js, src/plugins/animeinfo.js
Adds !when to check airing and upcoming anime airing times. Anime data is retrieved through Anilist API.
=> Add !when to check airing and upcoming anime airing times.

src/plugins/animeinfo.js
Adds !animetoday command to list the anime airing in the next 18 hours, sorted by air time.
=> Add !animetoday

src/plugins/animeinfo.js
Adds AniList links to !when and !today.
=> Add AniList link(s) to !when and !today

config/default.json5, package.json, src/index.js, src/plugins/youtube.js
Adds !yt to search for Youtube videos. Requires Youtube API key: https://www.slickremix.com/docs/get-api-key-for-youtube/.
=> Add !yt to search for Youtube videos

src/plugins/animeinfo.js
Fixes "airs in..." message when there's less than one minute left to airing for an anime.
=> Fix time until airing when there's less than a minute left

src/plugins/animeinfo.js
Reverts AlexKolpa/twodee-discord#23
=> Revert "Filter !when results to those matching the query"

src/plugins/animeinfo.js
Since Anilist API returns also results that don't match the given query, adds manual filtering to the results returned from the API.
=> Filter !when results to those matching the query

src/plugins/animeinfo.js
Fixes !when to display the correct number of search results found. Also a minor fix to displayed time left until airing when the time left is x hours and 0 minutes.
=> Search improvements

package.json, src/plugins/animeinfo.js, yarn.lock
!when will also return anime that have finished airing. For anime that finished over a year ago the season and the year is shown, otherwise the time since it finished.
!when will now show the time since the previous episode aired when it aired less than two days ago.
Increases the maximum number of search results returned by !when to 5, and the time period of !today to 24 hours.
=> Aired anime enhancements

src/plugins/choose.js
There often seems to be confusion as to which is the correct command, so let's support both of them.
=> support both !choose and !choice

src/plugins/reddit.js
Reddit post title or usernames can have characters that Discord handles as markdown, e.g. Reddit username \_Eltanin\_ is shown as _Eltanin_. Adds escaping for the characters in Reddit posts.
=> Escape markdown in Reddit posts

config/default.json5, package.json, src/index.js, src/plugins/eventlog.js, yarn.lock
Keeps log of reaction usage in local database. Adds command !reactions :reaction: which shows how many times the reaction has been used, and !topreactions, which lists the most used reactions.
Reactions in DMs or on own messages are not counted.
=> Reaction log

src/plugins/eventlog.js
Emoji that the bot doesn't have access are now only shown by their name in any response messages.
=> Add handling for emoji from other servers

package.json, src/index.js, src/plugins/danbooru.js, yarn.lock
Danbooru plugin with custom command support. For all your catgirl needs.
RFR
=> Set up danbooru plugin

src/plugins/animeinfo.js
Show only anime originating from Japan in !today. Add !tomorrow to get tomorrow's anime (between next 24-48h).
=> Jp anime only
